name: Test SSH Connection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.TRAYECTO3_KEY }}

      - name: Debug private key
        run: |
          echo "${{ secrets.TRAYECTO3_KEY }}" > private-key
          cat private-key

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TRAYECT03_USER }}@${{ secrets.TRAYECTO3_HOST }} "echo 'Hello, VPS!'"